baseURL = "https://blog.bespinian.io/"
languageCode = "en-us"
title = "bespinian Blog"
theme = "tale"
publishDir = "docs"
copyright = "&copy; <a href=\"https://bespinian.io\">bespinian</a> 2020"
disqusShortname = "berndsgnch"
googleAnalytics = "UA-132338301-2"

[params]
css = ["custom.css"]

[params.highlight]
style = "androidstudio"
languages = [
  "bash",
  "go",
  "html",
  "javascript",
  "json",
  "nginx",
  "php",
  "typescript",
  "yaml",
]

[[params.social]]
url = "https://bespinian.io/"
alt_text = "bespinian website"
icon_file = "globe.svg"

[[params.social]]
url = "https://github.com/bespinian"
alt_text = "bespinian on GitHub"
icon_file = "github.svg"

[[params.social]]
url = "https://twitter.com/bespinian"
alt_text = "bespinian on Twitter"
icon_file = "twitter.svg"

[[params.social]]
url = "/index.xml"
alt_text = "The bespinian blog RSS feed"
icon_file = "rss.svg"
