baseURL = "https://blog.bespinian.io/"
languageCode = "en-us"
title = "bespinian Blog"
theme = "tale"
publishDir = "docs"
copyright = "&copy; <a href=\"https://bespinian.io\">bespinian</a> 2020"
disqusShortname = "berndsgnch"
googleAnalytics = "UA-132338301-2"

[params]
css = ["custom.css"]

[params.highlight]
style = "androidstudio"
languages = [
  "bash",
  "go",
  "html",
  "javascript",
  "json",
  "nginx",
  "php",
  "typescript",
  "yaml",
]

[[params.social]]
url = "https://bespinian.io/"
fa_icon = "fa-globe"

[[params.social]]
url = "https://github.com/bespinian"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/bespinian"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
