title = "bespinian Blog"
baseURL = "https://blog.bespinian.io/"
languageCode = "en-us"
theme = "tale"
publishDir = "docs"
disqusShortname = "berndsgnch"
googleAnalytics = "UA-132338301-2"
enableRobotsTXT = true

[author]
  name = "bespinian"
  homepage = "https://bespinian.io"

[params]
css = ["custom.css"]

[[params.social]]
url = "https://bespinian.io/"
alt_text = "bespinian website"
icon_file = "globe.svg"

[[params.social]]
url = "https://github.com/bespinian"
alt_text = "bespinian on GitHub"
icon_file = "github.svg"

[[params.social]]
url = "https://twitter.com/bespinian"
alt_text = "bespinian on Twitter"
icon_file = "twitter.svg"

[[params.social]]
url = "/index.xml"
alt_text = "The bespinian blog RSS feed"
icon_file = "rss.svg"
