baseURL = "https://blog.bespinian.io/"
languageCode = "en-us"
title = "be|spinian Blog"
theme = "hemingway"
publishDir = "docs"
disqusShortname = "berndsgnch"
googleAnalytics = "UA-22629901-2"

[params]

[params.highlight]
style = "androidstudio"
languages = ["go", "typescript", "yaml"]

[[params.social]]
url = "https://github.com/bespinian"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/bespinian"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
