title = "bespinian Blog"
baseURL = "https://blog.bespinian.io/"
languageCode = "en-us"
theme = "tale"
disqusShortname = "berndsgnch"
googleAnalytics = "G-CQC3K0KBY5"
enableRobotsTXT = true

[author]
  name = "bespinian"
  homepage = "https://bespinian.io"

[params]
description = "The bespinian blog - All about cloud computing, containers, Kubernetes, AWS, Azure and much more"
css = ["custom.css"]

[[params.social]]
url = "https://bespinian.io/"
alt_text = "bespinian website"
icon_file = "globe.svg"

[[params.social]]
url = "https://github.com/bespinian"
alt_text = "bespinian on GitHub"
icon_file = "github.svg"

[[params.social]]
url = "https://twitter.com/bespinian"
alt_text = "bespinian on Twitter"
icon_file = "twitter.svg"

[[params.social]]
url = "https://www.youtube.com/channel/UCBQD1IedufccsRXqC_hypyg/playlists"
alt_text = "bespinian on YouTube"
icon_file = "youtube.svg"

[[params.social]]
url = "/index.xml"
alt_text = "The bespinian blog RSS feed"
icon_file = "rss.svg"
