name: Lint and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: sudo npm install --global prettier
      - run: prettier --check content
